### ISSUE TITLE
[FEATURE] Java Parsing

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooJava#1]
**Describe the solution you'd like**
Make it possible to parse Java code into the various Java types available in the project.

**Is your feature request related to a problem? Please describe.**
Not really

**Describe alternatives you've considered**
None

**Additional context**
Note: This issue originally dealt with a single parser class called JavaParser (at some point possibly it was named BaseJavaParser), where all types were handled entirely in one class, but was split into multiple parsing classes each handling their own specific type to be parsed. We still have FullJavaParser, which will determine what is being parsed.

**Changes TODO**
- [x] ParsingPojo (a record class containing nextTokenIndex and JavaCodeType, to be used as the results of a successful parsing operation)
- [x] JavaParsingException (an exception class to be thrown by parsing methods when there are errors in parsing the given Java object)
- [x] AbstractJavaParser (base parsing class containing shared regular expressions and methods used in multiple parsers)
  - [x] VISIBILITY_REGEX
  - [x] STATIC_REGEX
  - [x] FINAL_REGEX
  - [x] MODIFIERS_REGEX (currently combined visibility + static + final, but should be changed so order doesn't matter and support more modifiers)
  - [x] JavaCodeTypes determineFieldOrMethod (determines whether we're looking at a field or method given the currentToken and collection of tokens)
- [x] FullJavaParser (can parse any type from a String)
  - [x] JavaCodeType parseType(String content) (must support all types, will call other parsers to handle actual parsing and then use combineTypes to handle combining the pieces together if needed, this will basically split on whitespace and handle tokens for parsing)
    - [x] JavaSingleLineComment
    - [x] JavaMultiLineComment
    - [x] Javadoc
    - [x] JavaPackageDeclaration
    - [x] JavaImportStatement
    - [x] JavaAnnotation
    - [x] JavaField
    - [x] JavaMethod
    - [x] JavaClass
  - [x] JavaCodeType combineTypes(List<JavaCodeType> types) (takes a List of JavaCodeType objects in order and combines them if possible - e.g. if you have a package declaration, then import statements, then a class, these combine into a JavaClass)
- [x] Comment Types
  - [x] JavaSingleLineCommentParser (#21)
  - [x] JavaMultiLineCommentParser (#22)
  - [x] JavadocParser (#23)
- [x] Code Types
  - [x] JavaPackageDeclarationParser (#24)
  - [x] JavaImportStatementParser (#25)
  - [x] JavaAnnotationParser (#26)
  - [x] JavaFieldParser (#27)
  - [x] JavaMethodParser (#28)
  - [x] JavaTypeWithModifiersParser (used when you hit a modifier and don't yet know if it's a class, field, method, etc.)
- [x] Class Types
  - [x] JavaClassParser (#29)
- [x]  Other
  - [x] Support abstract for class and method

**Comment by Tadukoo** [comment]
Closing this now - note that this is for parsing for Beta v.0.5 - there will be future parsing tasks for future versions (e.g. a future version will parse interfaces even though we're not now since we don't have a class to hold interface data)
