### ISSUE TITLE
[FEATURE] Beta v.0.5 Epic

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooJava#10]
**Describe the solution you'd like**
This ticket is being used for all the features of Beta v.0.5, since they're all related.

**Is your feature request related to a problem? Please describe.**
Not really

**Describe alternatives you've considered**
None

**Additional context**
N/A

**The Mega List**
- [ ] The various types
  - [ ] All types
    - [x] Ability to copy a type to another (e.g. EditableJavaClass to UneditableJavaClass) (#9)
    - [ ] Ability to parse a type from a String (builder methods)
  - [x] JavaPackageDeclaration (#12)
  - [x] JavaImportStatement (#13)
  - [x] JavaSingleLineComment (#15)
  - [x] JavaMultiLineComment (#16)
  - [x] JavaAnnotation
    - [x] Ability for annotations to have parameters (#2)
    - [x] Map for parameters (for easier grabbing of them if they're not in the order we want necessarily) (#18)
  - [x] JavaField
    - [x] Should not require Visibility (#3)
    - [x] Should not have section comment (#5)
  - [x] JavaMethod
    - [x] Should not have section comment (#6)
    - [x] Allow to be final (#7)
    - [x] GetUniqueName (#14)
  - [x] JavaClass
    - [x] Allow to be final (#8)
    - [x] Easy builder/set methods for package name and imports (instead of having to build a full package declaration / import statement yourself since they're simple) (was done as part of #4)
    - [x] Maps for inner classes, fields, and methods (for easier grabbing of them if they're not in the order we want necessarily) (#20)
    - [x] The ability to specify the order of things in the class
    - [x] The ability to include comments (both single-line and multi-line) in class
    - [x] Allow to be abstract
    - [x] Allow to have "implements InterfaceNames" (#19)
- [ ] Miscellaneous Interfaces / Constants
  - [x] JavaTokens (#4)
  - [x] JavaCodeTypes (#11)
  - [ ] JavaClassType
- [ ] Java Parsing (#1)
- [ ] Java Validation
  - [ ] Determining canonical class names within a class
