### ISSUE TITLE
[FEATURE] Release 1.0 Goals

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooJava#17]
**Describe the solution you'd like**
This is used as a list of all the goals for release 1.0, to be used to help figure out how to divide them up

**Is your feature request related to a problem? Please describe.**
Not really

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Changes TODO**
- [ ] Base Interfaces/Constants/Classes
  - [ ] JavaTokens - interface for tokens used in the various java code
    - [x] SEMICOLON (Beta v.0.5)
    - [x] Tokens - basic Java tokens
      - [x] package (Beta v.0.5)
      - [x] import (Beta v.0.5)
      - [x] class (Beta v.0.5)
      - [x] throws (Beta v.0.5)
      - [x] extends (Beta v.0.5)
    - [x] Not-So-Proper Tokens - tokens used by Java that are symbols
      - [x] Javadoc Start Token - /** (Beta v.0.5)
      - [x] Javadoc Line Token - * (Beta v.0.5)
      - [x] MultiLine Comment Start Token - /* (Beta v.0.5)
      - [x] MultiLine Comment End Token - */ (Beta v.0.5)
      - [x] Single Line Comment Token - // (Beta v.0.5)
      - [x] Annotation Start Token - @ (Beta v.0.5)
      - [x] Parameter Open Token - ( (Beta v.0.5)
      - [x] Parameter Close Token - ) (Beta v.0.5)
      - [x] List Separator Token - , (Beta v.0.5)
      - [x] Block Open Token - { (Beta v.0.5)
      - [x] Block Close Token - } (Beta v.0.5)
      - [x] Assignment Operator Token - = (Beta v.0.5)
    - [x] Javadoc "Tokens" - tokens used in Javadoc annotations
      - [x] Javadoc Author Token (Beta v.0.5)
      - [x] Javadoc Version Token (Beta v.0.5)
      - [x] Javadoc Since Token (Beta v.0.5)
      - [x] Javadoc Param Token (Beta v.0.5)
      - [x] Javadoc Return Token (Beta v.0.5)
    - [x] Modifiers - modifiers on classes/fields/methods
      - [x] private (Beta v.0.5)
      - [x] protected (Beta v.0.5)
      - [x] public (Beta v.0.5)
      - [x] VISIBILITY_MODIFIERS (Set) - private, protected, public (Beta v.0.5)
      - [x] static (Beta v.0.5)
      - [x] final (Beta v.0.5)
      - [x] MODIFIERS (Set) - all of them (Beta v.0.5)
  - [x] JavaCodeType - base interface for all Java code classes
    - [x] Extends JavaTokens to allow the tokens to be used in classes (Beta v.0.5)
    - [x] JavaCodeTypes getJavaCodeType() - method to return the code type enum reference (Beta v.0.5)
  - [ ] JavaCodeTypes - enum for all the Java code types, referencing base classes
    - [x] UNKNOWN (for when we don't know a type) (Beta v.0.5)
    - [x] PACKAGE_DECLARATION (Beta v.0.5)
    - [x] IMPORT_STATEMENT (Beta v.0.5)
    - [x] JAVADOC (Beta v.0.5)
    - [x] MULTI_LINE_COMMENT (Beta v.0.5)
    - [x] SINGLE_LINE_COMMENT (Beta v.0.5)
    - [x] ANNOTATION (Beta v.0.5)
    - [x] TYPE_WITH_MODIFIERS (useful during parsing when we have modifiers, but don't yet know a more specific type) (Beta v.0.5)
    - [x] FIELD (Beta v.0.5)
    - [x] METHOD (Beta v.0.5)
    - [x] CLASS (Beta v.0.5)
    - [ ] ENUM
    - [ ] INTERFACE
    - [ ] RECORD
    - [ ] ANNOTATION_CLASS
    - [ ] PURE_CODE
    - [ ] VARIABLE_DECLARATION_OR_ASSIGNMENT
    - [ ] CONDITION
    - [ ] IF_BLOCK
    - [ ] FOR_LOOP
    - [ ] WHILE_LOOP
    - [ ] DO_WHILE_LOOP
  - [ ] JavaClassType - base class for enum, interface, class, record, and annotation class
  - [ ] PureJavaCode - base interface for Java code classes that are pure code (e.g. if block, for loop, etc.)
  - [x] Visibility - enum for visibility modifiers
    - [x] PUBLIC (Beta v.0.5)
    - [x] PROTECTED (Beta v.0.5)
    - [x] PRIVATE (Beta v.0.5)
    - [x] NONE (Beta v.0.5)
    - [x] String getToken() - returns the token from JavaTokens representing the Visibility (Beta v.0.5)
    - [x] static Visibility fromToken(String token) - grabs a Visibility reference using the given token (Beta v.0.5)
  - [ ] JavaType - class for a Java type reference (e.g. String, List<String>, Map<String, Object>, List<?>, etc.)
- [ ] Requirements for all JavaCodeType's
  - [ ] Implement JavaCodeType
  - [ ] Have a JavaCodeTypes enum reference
  - [ ] Copy method in builder
  - [ ] Editable boolean
  - [ ] Default Editable and Uneditable versions
- [ ] Java Code Types
  - [x] JavaPackageDeclaration - class for package declarations in classes
    - [x] boolean editable (Beta v.0.5)
    - [x] String packageName (Beta v.0.5)
  - [x] JavaImportStatement - class for import statements in classes
    - [x] boolean editable (Beta v.0.5)
    - [x] boolean isStatic (Beta v.0.5)
    - [x] String importName (Beta v.0.5)
  - [ ] JavaSingleLineComment - class for single line comments
  - [ ] JavaMultiLineComment - class for multi-line comments
  - [ ] Javadoc - class for javadocs in classes, fields, methods
  - [ ] JavaAnnotation - class for annotations
  - [ ] JavaField - class for fields
  - [ ] JavaMethod - class for methods
  - [ ] JavaClass - class for classes
  - [ ] JavaInterface - class for interfaces
  - [ ] JavaEnum - class for enums
  - [ ] JavaRecord - class for records
  - [ ] JavaAnnotationClass - class for annotation classes
- [ ] PureJavaCode Types
  - [ ] JavaVariableDeclarationOrAssignment - for a variable being assigned or declared
  - [ ] JavaCondition - for conditions (e.g. the condition part of a for loop)
  - [ ] JavaIfBlock - for an if block (including else-if and else blocks too)
  - [ ] JavaForLoop - for a for loop and its contents
  - [ ] JavaWhileLoop - for a while loop and its contents
  - [ ] JavaDoWhileLoop - for a do-while loop and its contents
- [ ] Java Parsing
  - [ ] FullJavaParser
    - [ ] JavaCodeType parseCodeType(String content) - main method to parse any JavaCodeType
      - [ ] Package Declaration - call JavaPackageDeclarationParser's method (Beta v.0.5)
      - [ ] Import Statement - call JavaImportStatementParser's method (Beta v.0.5)
      - [ ] Single Line Comment - call JavaSingleLineCommentParser's method (Beta v.0.5)
      - [ ] Multi-Line Comment - call JavaMultiLineCommentParser's method (Beta v.0.5)
      - [ ] Javadoc - call JavadocParser's method (Beta v.0.5)
      - [ ] Annotation - call JavaAnnotationParser's method (Beta v.0.5)
      - [ ] Type with Modifiers - call JavaTypeWithModifiersParser's method (Beta v.0.5)
      - [ ] Field - call JavaFieldParser's method (Beta v.0.5)
      - [ ] Method - call JavaMethodParser's method (Beta v.0.5)
      - [ ] Class - call JavaClassParser's method (Beta v.0.5)
      - [ ] Interface
      - [ ] Enum
      - [ ] Record
      - [ ] Annotation Class
  - [ ] Other Parsers
    - [ ] Package Declaration (Beta v.0.5)
      - [ ] JavaPackageDeclaration parsePackageDeclaration(String content) - used for full parsing (Beta v.0.5)
      - [ ] ParsingPojo parsePackageDeclaration(List<String> tokens, int startToken) - used once tokens have already been determined, mainly by FullJavaParser (Beta v.0.5)
    - [ ] Import Statement (Beta v.0.5)
      - [ ] JavaImportStatement parseImportStatement(String content) - used for full parsing (Beta v.0.5)
      - [ ] ParsingPojo parseJavaImportStatement(List<String> tokens, int startToken) - used once tokens have already been determined, mainly by FullJavaParser (Beta v.0.5)
    - [ ] Single Line Comment (Beta v.0.5)
      - [ ] JavaSingleLineComment parseSingleLineComment(String content) - used for full parsing (Beta v.0.5)
      - [ ] ParsingPojo parseSingleLineComment(List<String> tokens, int startToken) - used once tokens have already been determined, mainly by FullJavaParser (Beta v.0.5)
    - [ ] Multi-Line Comment (Beta v.0.5)
      - [ ] JavaMultiLineComment parseMultiLineComment(String content) - used for full parsing (Beta v.0.5)
      - [ ] ParsingPojo parseMultiLineComment(List<String> tokens, int startToken) - used once tokens have already been determined, mainly by FullJavaParser (Beta v.0.5)
    - [ ] Javadoc
    - [ ] Annotation
    - [ ] Type with Modifiers
      - [ ] Field
      - [ ] Method
      - [ ] Class
    - [ ] Field
    - [ ] Method
    - [ ] Class
    - [ ] Interface
    - [ ] Enum
    - [ ] Record
    - [ ] Annotation Class
  - [ ] Pure Java Code Parsing
    - [ ] Variable Declaration or Assignment
    - [ ] Condition
    - [ ] If Block
    - [ ] For Loop
    - [ ] While Loop
    - [ ] Do-While Loop
- [ ] Java Validation
- [ ] Testing
  - [ ] The base testing
  - [ ] Advanced parse/validation testing - testing of classes I wrote to ensure that the parsing and validation logic works correctly for real examples and not just the simple examples made for the base testing
    - [ ] Tadukoo Util project classes
    - [ ] Tadukoo Java project classes
    - [ ] `@UltimatePower` classes? (relevant because UltimatePower relies on this)
    - [ ] Tadukoo Form classes? (relevant because it's the first use of UltimatePower, so using this ultimately)
